### ISSUE TITLE
@conda-forge-admin, please add noarch: python

### ISSUE THREAD

**Issue by williamjamir** [conda-forge/pytest-selenium-feedstock#4]

**Comment by isuruf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by nicoddemus** [comment]
I believe this phrase [must be made in a PR](https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-add-noarch-python) to have an effect:

> Entering the above phrase in a PR of a feedstock will add noarch: python to the build and rerender the feedstock for you.
